[2025-10-07 21:26:07] ValueError: Tentativa de login com usuário não existente.
